//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANSWER
    {
        public long ID { get; set; }
        public Nullable<long> PARTY { get; set; }
        public Nullable<long> QUESTION { get; set; }
        public Nullable<long> OPTION { get; set; }
    
        public virtual OPTION OPTIONnav { get; set; }
        public virtual QUESTION QUESTIONnav { get; set; }
        public virtual PARTY PARTYnav { get; set; }
    }
}
