//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElectionSqliteContext : DbContext
    {
        public ElectionSqliteContext()
            : base("name=ElectionSqliteContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANSWER> ANSWERs { get; set; }
        public virtual DbSet<ELECTION> ELECTIONs { get; set; }
        public virtual DbSet<OPTION> OPTIONs { get; set; }
        public virtual DbSet<PARTY> PARTies { get; set; }
        public virtual DbSet<QUESTION> QUESTIONs { get; set; }
    }
}
